<project>
  ...
  <build>
    ...
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.1.2</version>
        <executions>
          <execution>
            <id>purge-local-repository</id>
            <goals>
              <goal>purge-local-repository</goal>
            </goals>
            <configuration>
              <actTransitively>false</actTransitively>
              <reResolve>false</reResolve>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  ...
</project>
