// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.constant;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import java.util.Optional;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

@RunWith(MockitoJUnitRunner.class)
public class ResponseCode_getMessageByStatusCode_f9b6b99001_Test {

    @Before
    public void setUp() {
        // TODO: Initialize any necessary data or state for your tests here.
    }

    @Test
    public void testGetMessageByStatusCode_Success() {
        // TODO: Replace the status code with an actual status code that exists in your ResponseCode enum.
        int statusCode = 200; 
        Optional<ResponseCode> result = ResponseCode.getMessageByStatusCode(statusCode);

        // Assert that the result is not empty (i.e., a ResponseCode was found with the given status code).
        assertFalse(result.isEmpty());

        // Assert that the status code of the resulting ResponseCode matches the status code we used to search.
        assertEquals(statusCode, result.get().getCode());
    }

    @Test
    public void testGetMessageByStatusCode_Failure() {
        // TODO: Replace the status code with a status code that does not exist in your ResponseCode enum.
        int statusCode = 999; 
        Optional<ResponseCode> result = ResponseCode.getMessageByStatusCode(statusCode);

        // Assert that the result is empty (i.e., no ResponseCode was found with the given status code).
        assertEquals(Optional.empty(), result);
    }
}
