// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

@Test
public void testService_WhenCustomerIsLoggedInAndCartIsUpdated() throws IOException, ServletException {
    request.setSession(session);
    session.setAttribute("role", UserRole.CUSTOMER);
    session.setAttribute("items", "1,2");
    session.setAttribute("qty_1", 3);
    session.setAttribute("qty_2", 4);

    Book book1 = new Book();
    book1.setBarcode("1");
    book1.setPrice(100);

    Book book2 = new Book();
    book2.setBarcode("2");
    book2.setPrice(200);

    List<Book> books = Arrays.asList(book1, book2);

    when(request.getRequestDispatcher("CustomerHome.html")).thenReturn(requestDispatcher);
    when(bookService.getBooksByCommaSeperatedBookIds(anyString())).thenReturn(books);

    new CartServlet().service(request, response);

    verify(requestDispatcher, times(1)).include(request, response);
    verify(session, times(1)).setAttribute("cartItems", books);
    verify(session, times(1)).setAttribute("amountToPay", 1400.0);
}
