// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package servlets;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import com.bittercode.model.Book;
import com.bittercode.model.Cart;

public class CartServlet_getRowData_4081c10d3b_Test {
    private CartServlet cartServlet;
    private Cart cart;
    private Book book;

    @BeforeEach
    public void setup() {
        cartServlet = new CartServlet();
        cart = Mockito.mock(Cart.class);
        book = Mockito.mock(Book.class);
        Mockito.when(cart.getBook()).thenReturn(book);
    }

    @Test
    public void testGetRowData() {
        Mockito.when(book.getBarcode()).thenReturn("123456");
        Mockito.when(book.getName()).thenReturn("Test Book");
        Mockito.when(book.getAuthor()).thenReturn("Test Author");
        Mockito.when(book.getPrice()).thenReturn(100.0);
        Mockito.when(cart.getQuantity()).thenReturn(2);

        String expectedOutput = "    <tr>\r\n"
                + "      <th scope=\"row\">123456</th>\r\n"
                + "      <td>Test Book</td>\r\n"
                + "      <td>Test Author</td>\r\n"
                + "      <td><span>&#8377;</span> 100.0</td>\r\n"
                + "      <td><form method='post' action='cart'><button type='submit' name='removeFromCart' class=\"glyphicon glyphicon-minus btn btn-danger\"></button> "
                + "<input type='hidden' name='selectedBookId' value='123456'/>"
                + "2 <button type='submit' name='addToCart' class=\"glyphicon glyphicon-plus btn btn-success\"></button></form></td>\r\n"
                + "      <td><span>&#8377;</span> 200.0</td>\r\n"
                + "    </tr>\r\n";

        String actualOutput = cartServlet.getRowData(cart);

        assertEquals(expectedOutput, actualOutput);
    }

    @Test
    public void testGetRowDataWithNullBook() {
        Mockito.when(cart.getBook()).thenReturn(null);

        String expectedOutput = "    <tr>\r\n"
                + "      <th scope=\"row\">null</th>\r\n"
                + "      <td>null</td>\r\n"
                + "      <td>null</td>\r\n"
                + "      <td><span>&#8377;</span> null</td>\r\n"
                + "      <td><form method='post' action='cart'><button type='submit' name='removeFromCart' class=\"glyphicon glyphicon-minus btn btn-danger\"></button> "
                + "<input type='hidden' name='selectedBookId' value='null'/>"
                + "null <button type='submit' name='addToCart' class=\"glyphicon glyphicon-plus btn btn-success\"></button></form></td>\r\n"
                + "      <td><span>&#8377;</span> null</td>\r\n"
                + "    </tr>\r\n";

        String actualOutput = cartServlet.getRowData(cart);

        assertEquals(expectedOutput, actualOutput);
    }
}
