// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package servlets;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import com.bittercode.constant.BookStoreConstants;
import com.bittercode.service.UserService;
import com.bittercode.service.impl.UserServiceImpl;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;

public class LogoutServlet_doGet_5d033d49c5_Test {

    @Mock
    HttpServletRequest request;

    @Mock
    HttpServletResponse response;

    @Mock
    UserService authService;

    @Mock
    PrintWriter printWriter;

    @Mock
    RequestDispatcher requestDispatcher;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
        when(response.getWriter()).thenReturn(printWriter);
        when(request.getRequestDispatcher(anyString())).thenReturn(requestDispatcher);
    }

    @Test
    public void testDoGet_LogoutSuccess() throws IOException, ServletException {
        when(authService.logout(any())).thenReturn(true);
        new LogoutServlet_doGet_5d033d49c5().doGet(request, response);
        verify(printWriter, times(1)).println("<table class=\"tab\"><tr><td>Successfully logged out!</td></tr></table>");
    }

    @Test
    public void testDoGet_LogoutFailure() throws IOException, ServletException {
        when(authService.logout(any())).thenReturn(false);
        new LogoutServlet_doGet_5d033d49c5().doGet(request, response);
        verify(printWriter, never()).println("<table class=\"tab\"><tr><td>Successfully logged out!</td></tr></table>");
    }
}
