// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package servlets;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.io.PrintWriter;
import java.io.StringWriter;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.verify;

public class RemoveBookServlet_showRemoveBookForm_6d52b26f73_Test {

    @Mock
    private PrintWriter printWriter;

    private StringWriter stringWriter;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        stringWriter = new StringWriter();
    }

    @Test
    public void testShowRemoveBookForm() {
        printWriter = new PrintWriter(stringWriter);

        showRemoveBookForm(printWriter);
        
        String form = "<form action=\"removebook\" method=\"post\" class='my-5'>\r\n"
                + "        <table class=\"tab\">\r\n"
                + "        <tr>\r\n"
                + "            <td>\r\n"
                + "                <label for=\"bookCode\">Enter BookId to Remove </label>\r\n"
                + "                <input type=\"text\" name=\"bookId\" placeholder=\"Enter Book Id\" id=\"bookCode\" required>\r\n"
                + "                <input class=\"btn btn-danger my-2\" type=\"submit\" value=\"Remove Book\">\r\n"
                + "            </td>\r\n"
                + "        </tr>\r\n"
                + "\r\n"
                + "        </table>\r\n"
                + "    </form>";
        
        assertEquals(form, stringWriter.toString());
    }

    @Test
    public void testShowRemoveBookForm_PrintWriterException() {
        try {
            showRemoveBookForm(printWriter);
        } catch (Exception e) {
            verify(printWriter).println("<form action=\"removebook\" method=\"post\" class='my-5'>\r\n"
                    + "        <table class=\"tab\">\r\n"
                    + "        <tr>\r\n"
                    + "            <td>\r\n"
                    + "                <label for=\"bookCode\">Enter BookId to Remove </label>\r\n"
                    + "                <input type=\"text\" name=\"bookId\" placeholder=\"Enter Book Id\" id=\"bookCode\" required>\r\n"
                    + "                <input class=\"btn btn-danger my-2\" type=\"submit\" value=\"Remove Book\">\r\n"
                    + "            </td>\r\n"
                    + "        </tr>\r\n"
                    + "\r\n"
                    + "        </table>\r\n"
                    + "    </form>");
        }
    }

    private static void showRemoveBookForm(PrintWriter pw) {
        String form = "<form action=\"removebook\" method=\"post\" class='my-5'>\r\n"
                + "        <table class=\"tab\">\r\n"
                + "        <tr>\r\n"
                + "            <td>\r\n"
                + "                <label for=\"bookCode\">Enter BookId to Remove </label>\r\n"
                + "                <input type=\"text\" name=\"bookId\" placeholder=\"Enter Book Id\" id=\"bookCode\" required>\r\n"
                + "                <input class=\"btn btn-danger my-2\" type=\"submit\" value=\"Remove Book\">\r\n"
                + "            </td>\r\n"
                + "        </tr>\r\n"
                + "\r\n"
                + "        </table>\r\n"
                + "    </form>";
        pw.println(form);
    }
}
