// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package servlets;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import com.bittercode.model.Book;
import com.bittercode.servlet.StoreBookServlet;

public class StoreBookServlet_getRowData_9c91c33644_Test {
    private StoreBookServlet storeBookServlet;

    @BeforeEach
    public void setUp() {
        storeBookServlet = new StoreBookServlet();
    }

    @Test
    public void testGetRowData() {
        Book book = mock(Book.class);
        String barcode = "1234567890";
        String name = "Test Book";
        String author = "Test Author";
        double price = 100.0;
        int quantity = 10;

        String expected = "    <tr>\r\n"
                + "      <th scope=\"row\">" + barcode + "</th>\r\n"
                + "      <td>" + name + "</td>\r\n"
                + "      <td>" + author + "</td>\r\n"
                + "      <td><span>&#8377;</span> " + price + "</td>\r\n"
                + "      <td>" + quantity + "      </td>\r\n"
                + "      <td><form method='post' action='updatebook'>"
                + "          <input type='hidden' name='bookId' value='" + barcode + "'/>"
                + "          <button type='submit' class=\"btn btn-success\">Update</button>"
                + "          </form>"
                + "    </tr>\r\n";

        assertEquals(expected, storeBookServlet.getRowData(book));
    }

    @Test
    public void testGetRowData_NullBook() {
        Book book = null;
        String expected = "    <tr>\r\n"
                + "      <th scope=\"row\">null</th>\r\n"
                + "      <td>null</td>\r\n"
                + "      <td>null</td>\r\n"
                + "      <td><span>&#8377;</span> null</td>\r\n"
                + "      <td>null      </td>\r\n"
                + "      <td><form method='post' action='updatebook'>"
                + "          <input type='hidden' name='bookId' value='null'/>"
                + "          <button type='submit' class=\"btn btn-success\">Update</button>"
                + "          </form>"
                + "    </tr>\r\n";

        assertEquals(expected, storeBookServlet.getRowData(book));
    }
}
