// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class Address_getAddressLine2_0b992a6264_Test {

    @Mock
    private Address address;

    @Before
    public void setUp() {
        when(address.getAddressLine2()).thenReturn("123 Main St");
    }

    @Test
    public void testGetAddressLine2_Success() {
        String expected = "123 Main St";
        String actual = address.getAddressLine2();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetAddressLine2_Failure() {
        String expected = "456 Maple Ave";
        String actual = address.getAddressLine2();
        assertEquals(expected, actual);
    }
}
