// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Address_setAddressLine1_56e56146ea_Test {

    @InjectMocks
    private Address address;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetAddressLine1_Success() {
        String expectedAddressLine1 = "123 Main Street";
        address.setAddressLine1(expectedAddressLine1);
        assertEquals(expectedAddressLine1, address.getAddressLine1());
    }

    @Test
    public void testSetAddressLine1_Null() {
        String expectedAddressLine1 = null;
        address.setAddressLine1(expectedAddressLine1);
        assertEquals(expectedAddressLine1, address.getAddressLine1());
    }

}
