// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Address_setPhone_fec6a16ac9_Test {

    @InjectMocks
    private Address address;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetPhone_Success() {
        String expectedPhone = "1234567890";
        address.setPhone(expectedPhone);
        assertEquals(expectedPhone, address.getPhone());
    }

    @Test
    public void testSetPhone_Null() {
        String expectedPhone = null;
        address.setPhone(expectedPhone);
        assertEquals(expectedPhone, address.getPhone());
    }
}
