// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Address_setPinCode_5e891e63de_Test {

    private Address address;

    @BeforeEach
    public void setup() {
        address = new Address();
    }

    @Test
    public void testSetPinCode_Success() {
        long expectedPinCode = 123456;
        address.setPinCode(expectedPinCode);
        assertEquals(expectedPinCode, address.getPinCode());
    }

    @Test
    public void testSetPinCode_Zero() {
        long expectedPinCode = 0;
        address.setPinCode(expectedPinCode);
        assertEquals(expectedPinCode, address.getPinCode());
    }

    @Test
    public void testSetPinCode_Negative() {
        long expectedPinCode = -123456;
        address.setPinCode(expectedPinCode);
        assertEquals(expectedPinCode, address.getPinCode());
    }
}
