// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.*;

@RunWith(MockitoJUnitRunner.class)
public class Address_setCity_13b9bc67c6_Test {
    
    private Address address;

    @Before
    public void setUp() {
        address = new Address();
    }

    @Test
    public void testSetCity() {
        String expectedCity = "New York";
        address.setCity(expectedCity);
        assertEquals(expectedCity, address.getCity());
    }

    @Test(expected = NullPointerException.class)
    public void testSetCityWithNull() {
        String city = null;
        address.setCity(city);
    }
}
