// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Book_setName_f5bd015150_Test {
    private Book book;

    @BeforeEach
    public void setUp() {
        book = new Book();
    }

    @Test
    public void testSetName() {
        String expectedName = "Test Book";
        book.setName(expectedName);
        assertEquals(expectedName, book.getName());
    }

    @Test
    public void testSetNameWithNull() {
        String expectedName = null;
        book.setName(expectedName);
        assertEquals(expectedName, book.getName());
    }
}
