// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class Book_getName_4ad76af4d7_Test {

    @InjectMocks
    private Book book;

    @BeforeEach
    public void setUp() {
        book.setName("Test Book");
    }

    @Test
    public void testGetName() {
        String expected = "Test Book";
        String actual = book.getName();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetNameWithNull() {
        book.setName(null);
        String expected = null;
        String actual = book.getName();
        assertEquals(expected, actual);
    }
}
