// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Book_setBarcode_4d962fe0af_Test {
    private Book book;

    @BeforeEach
    public void setUp() {
        book = new Book();
    }

    @Test
    public void testSetBarcode_Success() {
        String expectedBarcode = "1234567890";
        book.setBarcode(expectedBarcode);
        assertEquals(expectedBarcode, book.getBarcode());
    }

    @Test
    public void testSetBarcode_Empty() {
        String expectedBarcode = "";
        book.setBarcode(expectedBarcode);
        assertEquals(expectedBarcode, book.getBarcode());
    }
}
