// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Cart_getQuantity_2dd1a62113_Test {

    private Cart cart;

    @BeforeEach
    public void setup() {
        cart = new Cart();
    }

    @Test
    public void testGetQuantityWhenQuantityIsZero() {
        cart.setQuantity(0);
        int expectedQuantity = 0;
        int actualQuantity = cart.getQuantity();
        assertEquals(expectedQuantity, actualQuantity, "The quantity should be 0 when no items are added to the cart.");
    }

    @Test
    public void testGetQuantityWhenQuantityIsPositive() {
        cart.setQuantity(5);
        int expectedQuantity = 5;
        int actualQuantity = cart.getQuantity();
        assertEquals(expectedQuantity, actualQuantity, "The quantity should match the number of items added to the cart.");
    }

    //TODO: Add more test cases if needed
}
