// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import com.bittercode.constant.ResponseCode;

public class StoreException_getErrorMessage_c0ba7b8126_Test {

    @Mock
    private ResponseCode responseCode;

    @InjectMocks
    private StoreException storeException;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetErrorMessage_Success() {
        String expectedErrorMessage = "This is a test error message";
        when(responseCode.getErrorMessage()).thenReturn(expectedErrorMessage);

        String actualErrorMessage = storeException.getErrorMessage();

        assertEquals(expectedErrorMessage, actualErrorMessage, "Expected and actual error messages do not match");
    }

    @Test
    public void testGetErrorMessage_Failure() {
        String expectedErrorMessage = null;
        when(responseCode.getErrorMessage()).thenReturn(expectedErrorMessage);

        String actualErrorMessage = storeException.getErrorMessage();

        assertEquals(expectedErrorMessage, actualErrorMessage, "Expected and actual error messages do not match");
    }
}
