// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class StoreException_setStatusCode_528a56683e_Test {
    private StoreException storeException;

    @BeforeEach
    public void setUp() {
        storeException = new StoreException();
    }

    @Test
    public void testSetStatusCode_PositiveNumber() {
        int statusCode = 200; // TODO: Change this value as needed
        storeException.setStatusCode(statusCode);
        assertEquals(statusCode, storeException.getStatusCode(), "The status code should be set correctly");
    }

    @Test
    public void testSetStatusCode_Zero() {
        int statusCode = 0; // TODO: Change this value as needed
        storeException.setStatusCode(statusCode);
        assertEquals(statusCode, storeException.getStatusCode(), "The status code should be set correctly");
    }

    @Test
    public void testSetStatusCode_NegativeNumber() {
        int statusCode = -1;  // TODO: Change this value as needed
        storeException.setStatusCode(statusCode);
        assertEquals(statusCode, storeException.getStatusCode(), "The status code should be set correctly");
    }
}
