// Test generated by RoostGPT for test onlineBookStore using AI Type Open AI and AI Model gpt-4

package com.bittercode.model;

import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class User_getRoles_8108d1290f_Test {

    @InjectMocks
    User user;

    @Mock
    List<UserRole> roles;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetRoles_success() {
        UserRole role1 = new UserRole();
        role1.setRole("admin");
        UserRole role2 = new UserRole();
        role2.setRole("user");

        when(roles).thenReturn(Arrays.asList(role1, role2));

        List<UserRole> result = user.getRoles();

        assertEquals(2, result.size());
        assertEquals("admin", result.get(0).getRole());
        assertEquals("user", result.get(1).getRole());
    }

    @Test
    public void testGetRoles_empty() {
        when(roles).thenReturn(Arrays.asList());

        List<UserRole> result = user.getRoles();

        assertEquals(0, result.size());
    }
}
